services:
  server:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80" # 8080 is the port on your host machine, 80 is the port inside the container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  # php:
  # mysql:
  # composer:
  # npm:
  # artisan:
