services:
  server:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80" # 8080 is the port on your host machine, 80 is the port inside the container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php: # We created a Dockerfile for PHP because we need to install some extensions
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated # port is 9000 inside the container
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - ./env/mysql.env # environment variables for MySQL
    ports:
      - "3306:3306" # 3306 is the port on your host machine, 3306 is the port inside the container
    volumes:
      - ./mysql:/var/lib/mysql # persist data in ./mysql directory
  composer: # We created a Dockerfile for Composer because we need an ENTRYPOINT to run composer commands
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # npm:
  # artisan:
